[2023-09-13 17:34:15,696] INFO _log() L224  127.0.0.1 - - [13/Sep/2023 17:34:15] "GET /comment/all HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:35:59,702] INFO _log() L224  127.0.0.1 - - [13/Sep/2023 17:35:59] "PUT /comment/update?title=Apenas%20um%20amor HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:36:10,881] WARNING update_comment() L187  Erro ao adicionar usuário, Não foi possível salvar nova usuário :/ - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-comment!\mvp-comment-comments\app.py L187 
[2023-09-13 17:36:10,882] INFO _log() L224  127.0.0.1 - - [13/Sep/2023 17:36:10] "[31m[1mPUT /comment/update?title=Apenas%20um%20amor2 HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:36:19,147] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.95.8.98:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:36:26,169] INFO _log() L224  127.0.0.1 - - [13/Sep/2023 17:36:26] "[31m[1mPUT /comment/update?title=Apenas%20um%20amor000 HTTP/1.1[0m" 409 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:36:31,467] WARNING update_comment() L187  Erro ao adicionar usuário, Não foi possível salvar nova usuário :/ - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-comment!\mvp-comment-comments\app.py L187 
[2023-09-13 17:36:31,469] INFO _log() L224  127.0.0.1 - - [13/Sep/2023 17:36:31] "[31m[1mPUT /comment/update?title=Apenas%20um%20amor000 HTTP/1.1[0m" 400 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:37:41,737] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.95.8.98:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:37:44,478] INFO _log() L224  127.0.0.1 - - [13/Sep/2023 17:37:44] "GET /comment/all HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 17:38:38,411] INFO _log() L224  127.0.0.1 - - [13/Sep/2023 17:38:38] "PUT /comment/update?title=Apenas%20um%20amor44 HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:23:53,833] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.95.8.98:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:24:08,822] INFO _log() L224  127.0.0.1 - - [14/Sep/2023 22:24:08] "[33mGET /comment/id/1 HTTP/1.1[0m" 404 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:37:09,414] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.95.8.98:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:37:14,441] INFO _log() L224  127.0.0.1 - - [14/Sep/2023 22:37:14] "[33mGET /comment/id/1 HTTP/1.1[0m" 404 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:37:15,918] INFO _log() L224  127.0.0.1 - - [14/Sep/2023 22:37:15] "[33mGET /comment/id/1 HTTP/1.1[0m" 404 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:37:27,731] ERROR log_exception() L1449 Exception on /comment/id [GET] - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-comment!\mvp-comment-comments\app.py", line 190, in get_comments_id
    id = unquote(unquote(query.id))
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\urllib\parse.py", line 656, in unquote
    if '%' not in string:
TypeError: argument of type 'int' is not iterable
[2023-09-14 22:37:27,739] INFO _log() L224  127.0.0.1 - - [14/Sep/2023 22:37:27] "[35m[1mGET /comment/id?id=1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:40:28,861] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.95.8.98:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-14 22:40:31,211] INFO _log() L224  127.0.0.1 - - [14/Sep/2023 22:40:31] "[33mGET /comment/id?id=1 HTTP/1.1[0m" 404 - - call_trace=C:\Users\biaoz\PycharmProjects\18-paiting-project\venv\lib\site-packages\werkzeug\_internal.py L224 
